# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hairdressing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=6)),
                ('zipcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('description', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='citation',
            name='id_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='myhairdressing.Schedule'),
        ),
        migrations.AddField(
            model_name='citation',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to=settings.AUTH_USER_MODEL),
        ),
    ]
