# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhairdressing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressing',
            name='schedule_hairdressing',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado')], default=1, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.PositiveSmallIntegerField(choices=[(9, '09:00h'), (10, '10:00h'), (11, '11:00h'), (12, '12:00h'), (13, '13:00h'), (14, '14:00h'), (15, '15:00h'), (16, '16:00h'), (17, '17:00h'), (18, '18:00h'), (19, '19:00h'), (20, '20:00h')], default=1, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_hairdressing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='myhairdressing.Hairdressing'),
            preserve_default=False,
        ),
    ]
