# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhairdressing', '0002_auto_20160428_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressing',
            name='image',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='schedule_hairdressing',
            field=models.CharField(max_length=70),
        ),
    ]
