# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhairdressing', '0003_auto_20160429_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdressing',
            name='image',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
